"""Hindi words for Consiz's own windows (see i18n.py). The English sentence is the key; a missing key shows English.

Written in plain, everyday Hindi, keeping familiar English words people already use on a PC (Settings, PC, AI, Google,
Windows, shortcut names). Brand and product names stay in English. Placeholders such as {label} must stay as they are.
A native speaker should read this file once: send corrections as a pull request or in the team chat.
"""
from __future__ import annotations

HI: dict[str, str] = {
    # ------------------------------------------------------------------ answer window
    "Send ➤": "भेजें ➤",
    "■ Stop": "■ रोकें",
    "↺ New chat": "↺ नई बातचीत",
    "Copy all": "सब कॉपी करें",
    "Copied ✓": "कॉपी हो गया ✓",
    "Copy": "कॉपी",
    "Save as text": "टेक्स्ट के रूप में सहेजें",
    "Consiz answer": "Consiz उत्तर",
    "Close": "बंद करें",
    "You": "आप",
    "Consiz is thinking…": "Consiz सोच रहा है…",
    "Stopped.": "रोक दिया गया।",
    "Ask a follow-up…": "अगला सवाल पूछें…",
    "Ask about your PC…": "अपने पीसी के बारे में पूछें…",
    "Listening… speak, then pause": "सुन रहा हूँ… बोलिए, फिर रुकिए",
    "Ask about my PC": "मेरे पीसी के बारे में पूछें",
    "Reads program names, memory use and window titles on this PC":
        "इस पीसी पर प्रोग्राम के नाम, मेमोरी का उपयोग और विंडो के शीर्षक पढ़ता है",
    "Ask me anything about this PC. Tap a question or type your own:":
        "इस पीसी के बारे में कुछ भी पूछिए। कोई सवाल दबाइए या अपना खुद का लिखिए:",
    "What is slowing my PC down?": "मेरा पीसी किस वजह से धीमा हो रहा है?",
    "What am I working on right now?": "मैं अभी किस काम पर लगा हूँ?",
    "What starts with Windows?": "Windows के साथ क्या-क्या शुरू होता है?",
    "Is anything using the internet a lot?": "क्या कोई चीज़ इंटरनेट बहुत इस्तेमाल कर रही है?",
    "How full is my disk?": "मेरी डिस्क कितनी भरी है?",
    "Nothing was selected, so this is Ask about my PC.": "कुछ चुना नहीं गया था, इसलिए यह \"मेरे पीसी के बारे में पूछें\" है।",
    "Nothing was selected, so speak a question about this PC.": "कुछ चुना नहीं गया था, इसलिए इस पीसी के बारे में कोई सवाल बोलिए।",
    "New chat": "नई बातचीत",
    "Ask anything about your selected text": "अपने चुने हुए टेक्स्ट के बारे में कुछ भी पूछें",
    "Ask a question about the text you selected, or anything else.": "जो टेक्स्ट चुना है उसके बारे में, या किसी और चीज़ के बारे में सवाल पूछें।",
    "Processing…": "प्रक्रिया जारी है…",
    "Result": "नतीजा",
    "Web Context": "वेब संदर्भ",
    "Earlier chat": "पुरानी बातचीत",
    "Nothing to save yet": "अभी सहेजने के लिए कुछ नहीं है",
    "Saved: {path}": "सहेजा गया: {path}",
    "Could not save ({error})": "सहेजा नहीं जा सका ({error})",
    "Saved chat · {n} messages": "सहेजी हुई बातचीत · {n} संदेश",
    "Microphone problem": "माइक्रोफ़ोन की समस्या",
    "Voice problem": "आवाज़ की समस्या",
    "Nothing heard": "कुछ सुनाई नहीं दिया",
    "I did not hear anything. Tap the 🎙 button and try again.": "मुझे कुछ सुनाई नहीं दिया। 🎙 बटन दबाकर फिर कोशिश करें।",
    "No Speech Detected": "कोई आवाज़ नहीं मिली",
    "🎙 Listening… speak, then pause": "🎙 सुन रहा हूँ… बोलिए, फिर रुकिए",
    "⚡ Understanding what you said…": "⚡ आपकी बात समझ रहा हूँ…",
    "Selected text": "चुना हुआ टेक्स्ट",
    "Question": "सवाल",
    "File": "फ़ाइल",
    "Folder": "फ़ोल्डर",
    "Table": "तालिका",
    "Unsupported": "समर्थित नहीं",
    "Done": "हो गया",
    "Nothing selected": "कुछ चुना नहीं गया",
    "Unclear selection": "चयन साफ़ नहीं है",
    "Can't read this": "यह पढ़ा नहीं जा सकता",
    "Can't read this table": "यह तालिका पढ़ी नहीं जा सकती",
    "Took too long": "बहुत देर लग गई",
    "Not sent: looks private": "भेजा नहीं गया: निजी लगता है",
    "AI not reachable": "AI तक पहुँचा नहीं जा सका",
    "Please update Consiz: this version is no longer supported.": "कृपया Consiz अपडेट करें: यह संस्करण अब समर्थित नहीं है।",
    "It's not you, it's the AI. (key problem — check the .env file)": "गलती आपकी नहीं, AI की है। (कुंजी की समस्या — .env फ़ाइल देखें)",
    "It's not you, it's the AI. (too many requests — try again in a minute)": "गलती आपकी नहीं, AI की है। (बहुत ज़्यादा अनुरोध — एक मिनट बाद फिर कोशिश करें)",
    "It's not you, it's the AI. (request timed out — server is busy, please retry)": "गलती आपकी नहीं, AI की है। (अनुरोध का समय निकल गया — सर्वर व्यस्त है, कृपया फिर कोशिश करें)",
    "It's not you, it's the AI. (couldn't reach the model — check internet and retry)": "गलती आपकी नहीं, AI की है। (मॉडल तक नहीं पहुँच सके — इंटरनेट देखें और फिर कोशिश करें)",
    "⚠ The AI sent an empty answer. Try asking again.": "⚠ AI ने खाली उत्तर भेजा। फिर से पूछकर देखें।",
    "Please sign in again to continue.": "जारी रखने के लिए कृपया फिर से साइन इन करें।",
    "Open Storage settings": "स्टोरेज सेटिंग्स खोलें",
    "Open Startup apps settings": "स्टार्टअप ऐप्स की सेटिंग्स खोलें",
    "Open Installed apps": "इंस्टॉल किए ऐप्स खोलें",
    "Open Battery settings": "बैटरी सेटिंग्स खोलें",
    "Open Windows Update": "Windows Update खोलें",
    "Open Network settings": "नेटवर्क सेटिंग्स खोलें",
    "Open Task Manager": "Task Manager खोलें",
    "Open Disk Cleanup": "Disk Cleanup खोलें",
    "Open Downloads folder": "Downloads फ़ोल्डर खोलें",
    "Switch to: {title}": "इस पर जाएँ: {title}",
    "Close {app}: {title}": "{app} बंद करें: {title}",
    "Clear old temporary files": "पुरानी अस्थायी फ़ाइलें साफ़ करें",
    "Stop {item} starting with Windows": "{item} को Windows के साथ शुरू होने से रोकें",
    "Opened.": "खोल दिया।",
    "Switched.": "बदल दिया।",
    "That window is closed now.": "वह विंडो अब बंद हो चुकी है।",
    "This needs your confirmation first.": "इसके लिए पहले आपकी पुष्टि चाहिए।",
    "Actions are Windows-only for now.": "फ़िलहाल ये क्रियाएँ सिर्फ़ Windows में हैं।",
    "Closed.": "बंद कर दिया।",
    "Stopped.": "रोक दिया गया।",
    "Cancelled. Nothing was changed.": "रद्द किया गया। कुछ नहीं बदला।",
    "Nothing to clear: no temporary file is more than a day old.": "साफ़ करने को कुछ नहीं: कोई अस्थायी फ़ाइल एक दिन से पुरानी नहीं है।",
    "Deleted {n} files and freed {size}.": "{n} फ़ाइलें मिटाईं और {size} जगह खाली हुई।",
    "Consiz will only clear a folder named Temp.": "Consiz सिर्फ़ Temp नाम का फ़ोल्डर साफ़ करेगा।",
    "Turned off. It will not start with Windows next time.": "बंद कर दिया। अगली बार यह Windows के साथ शुरू नहीं होगा।",
    "That one is set for all users of this PC, so Windows asks for permission to change it. I opened Startup apps for you.":
        "यह इस पीसी के सभी उपयोगकर्ताओं के लिए सेट है, इसलिए इसे बदलने के लिए Windows अनुमति माँगता है। मैंने आपके लिए Startup apps खोल दिया है।",
    "Left running: it did not close by itself.": "चलता छोड़ दिया: वह अपने आप बंद नहीं हुआ।",
    "Consiz - close a program": "Consiz - प्रोग्राम बंद करें",
    "Consiz - force it to stop?": "Consiz - ज़बरदस्ती रोकें?",
    "Consiz - clear temporary files": "Consiz - अस्थायी फ़ाइलें साफ़ करें",
    "Consiz - startup program": "Consiz - स्टार्टअप प्रोग्राम",
    "Close this program?\n\n  {name}\n  Window: {title}\n\nConsiz asks it to close first, like pressing its X. If it asks you to save, answer there.":
        "यह प्रोग्राम बंद करें?\n\n  {name}\n  विंडो: {title}\n\nConsiz पहले उससे बंद होने को कहता है, जैसे उसका X दबाना। अगर वह सहेजने को पूछे तो वहीं जवाब दें।",
    "{name} did not close by itself (it may be stuck, or waiting for you to save).\n\nForce it to stop? Anything unsaved in it is lost.":
        "{name} अपने आप बंद नहीं हुआ (वह अटका हो सकता है, या आपके सहेजने का इंतज़ार कर रहा हो)।\n\nज़बरदस्ती रोकें? उसमें जो सहेजा नहीं है, वह खो जाएगा।",
    "Delete {count} temporary files ({size}) that are more than a day old?\n\n  Folder: {root}\n\nThese are leftovers that programs wrote and no longer need. Files that are in use are skipped. They are deleted for good (not moved to the Recycle Bin).":
        "{count} अस्थायी फ़ाइलें ({size}) मिटाएँ जो एक दिन से पुरानी हैं?\n\n  फ़ोल्डर: {root}\n\nये वे बचे-खुचे फ़ाइलें हैं जो प्रोग्रामों ने बनाईं और जिनकी अब ज़रूरत नहीं। जो फ़ाइलें इस्तेमाल में हैं, उन्हें छोड़ दिया जाता है। ये हमेशा के लिए मिट जाती हैं (Recycle Bin में नहीं जातीं)।",
    "Stop {name} from starting with Windows?\n\nThe program is not removed and nothing is deleted. You can turn it back on any time in Settings > Apps > Startup.":
        "{name} को Windows के साथ शुरू होने से रोकें?\n\nप्रोग्राम हटाया नहीं जाता और कुछ मिटाया नहीं जाता। आप कभी भी Settings > Apps > Startup में इसे फिर चालू कर सकते हैं।",
    "Consiz will not close this: {why}.": "Consiz इसे बंद नहीं करेगा: {why}।",
    "it is part of Windows or your security software": "यह Windows या आपके सुरक्षा सॉफ़्टवेयर का हिस्सा है",
    "it is Consiz itself, or the program that started Consiz": "यह खुद Consiz है, या वह प्रोग्राम जिसने Consiz शुरू किया",
    "it is a Windows program": "यह एक Windows प्रोग्राम है",
    "it belongs to another account": "यह किसी दूसरे खाते का है",
    "it has already closed": "यह पहले ही बंद हो चुका है",
    "Windows does not let Consiz change it (it may be running as administrator)": "Windows Consiz को इसे बदलने नहीं देता (यह administrator के रूप में चल रहा हो सकता है)",
    "{app} is running as administrator, so Consiz cannot read it. To use Consiz there, close Consiz and start it with a right-click on Consiz.exe > Run as administrator.":
        "{app} administrator के रूप में चल रहा है, इसलिए Consiz उसे पढ़ नहीं सकता। वहाँ Consiz इस्तेमाल करने के लिए Consiz बंद करें और Consiz.exe पर राइट-क्लिक करके \"Run as administrator\" से शुरू करें।",

    # ------------------------------------------------------------------ message boxes and notices (main.py)
    "Consiz - explain a picture": "Consiz - तस्वीर समझाएँ",
    "Consiz can explain this picture with the AI:\n\n  {label}\n\nThe picture itself is sent (shrunk), and passwords or other private details in a picture cannot be removed first. Nothing is stored.\n\nSend it?":
        "Consiz AI की मदद से यह तस्वीर समझा सकता है:\n\n  {label}\n\nतस्वीर खुद (छोटी करके) भेजी जाती है, और तस्वीर में मौजूद पासवर्ड या दूसरी निजी जानकारी पहले हटाई नहीं जा सकती। कुछ भी सहेजा नहीं जाता।\n\nभेजें?",
    "the picture on your clipboard (for example a screenshot), {size}": "आपके क्लिपबोर्ड की तस्वीर (जैसे स्क्रीनशॉट), {size}",
    "Consiz - Voice dictation": "Consiz - वॉइस डिक्टेशन",
    "Voice dictation needs a one-time download of the speech model (about {mb} MB) from Hugging Face.\n\nIt is kept on this PC. Your voice is turned into text on this PC and the audio is never uploaded; only the words you say are sent to the AI, like a typed question.\n\nDownload it now?":
        "वॉइस डिक्टेशन के लिए बोली पहचानने का मॉडल (लगभग {mb} MB) Hugging Face से एक बार डाउनलोड करना पड़ता है।\n\nयह इसी पीसी पर रखा जाता है। आपकी आवाज़ इसी पीसी पर टेक्स्ट में बदली जाती है और ऑडियो कभी अपलोड नहीं होता; केवल आपके बोले हुए शब्द AI को भेजे जाते हैं, जैसे टाइप किया हुआ सवाल।\n\nअभी डाउनलोड करें?",
    "Consiz - Ask about my PC": "Consiz - मेरे पीसी के बारे में पूछें",
    "Ask about my PC will look at, on this computer:\n  - names of running programs and how much memory/CPU they use\n  - titles of open windows (not what is inside them)\n  - disk space, battery, startup programs\n\nWhen you ask a question, this summary (with passwords/keys removed) is sent to the AI to answer you. Nothing is changed on your PC.\n\nAllow this?":
        "\"मेरे पीसी के बारे में पूछें\" इस कंप्यूटर पर यह देखेगा:\n  - चल रहे प्रोग्रामों के नाम और वे कितनी मेमोरी/CPU इस्तेमाल करते हैं\n  - खुली विंडो के शीर्षक (उनके अंदर क्या है, यह नहीं)\n  - डिस्क की जगह, बैटरी, स्टार्टअप प्रोग्राम\n\nजब आप सवाल पूछते हैं, तो यह सारांश (पासवर्ड/कुंजियाँ हटाकर) आपको उत्तर देने के लिए AI को भेजा जाता है। आपके पीसी में कुछ भी बदला नहीं जाता।\n\nइसकी अनुमति दें?",
    "Consiz - read window text": "Consiz - विंडो का टेक्स्ट पढ़ें",
    "Consiz wants to read the text inside:\n\n{titles}\n\nThis text (passwords and keys removed) is sent to the AI to answer your question. If an app (like a browser) does not share its text, a PICTURE of that window is sent instead - a picture cannot have secrets removed, so say No if anything private is on that window.\n\nNothing is changed or sent anywhere else. Allow for this session?":
        "Consiz इनके अंदर का टेक्स्ट पढ़ना चाहता है:\n\n{titles}\n\nयह टेक्स्ट (पासवर्ड और कुंजियाँ हटाकर) आपके सवाल का उत्तर देने के लिए AI को भेजा जाता है। अगर कोई ऐप (जैसे ब्राउज़र) अपना टेक्स्ट साझा नहीं करता, तो उसकी जगह उस विंडो की एक तस्वीर भेजी जाती है - तस्वीर से गोपनीय जानकारी हटाई नहीं जा सकती, इसलिए अगर उस विंडो में कुछ निजी है तो \"नहीं\" कहें।\n\nकुछ भी बदला या कहीं और नहीं भेजा जाता। इस सत्र के लिए अनुमति दें?",
    "Voice dictation is not included in this version of Consiz.": "इस संस्करण के Consiz में वॉइस डिक्टेशन शामिल नहीं है।",
    "Voice dictation is switched off in Settings.": "वॉइस डिक्टेशन Settings में बंद है।",
    "Downloading the voice model (about {mb} MB, one time)…": "वॉइस मॉडल डाउनलोड हो रहा है (लगभग {mb} MB, सिर्फ़ एक बार)…",
    "Downloading the voice model… {pct}%  ({done} of {total} MB)": "वॉइस मॉडल डाउनलोड हो रहा है… {pct}%  ({done} / {total} MB)",
    "Voice model download cancelled. It will ask again next time.": "वॉइस मॉडल का डाउनलोड रद्द हुआ। अगली बार फिर पूछा जाएगा।",
    "Could not download the voice model. Check your internet connection and try again. ({error})":
        "वॉइस मॉडल डाउनलोड नहीं हो सका। अपना इंटरनेट देखें और फिर कोशिश करें। ({error})",
    "Could not start the microphone ({detail}). Check that a microphone is connected and that Windows allows desktop apps to use it: Settings > Privacy & security > Microphone.":
        "माइक्रोफ़ोन शुरू नहीं हो सका ({detail})। देखें कि माइक्रोफ़ोन जुड़ा है और Windows डेस्कटॉप ऐप्स को उसे इस्तेमाल करने देता है: Settings > Privacy & security > Microphone।",
    "Consiz is already running in another window/process. Only one instance can listen for triggers.":
        "Consiz पहले से किसी दूसरी विंडो/प्रक्रिया में चल रहा है। ट्रिगर सुनने वाला एक ही हो सकता है।",
    "Consiz hit an unexpected error and had to stop.\n\nDetails were saved to:\n{path}\n\nPlease send that file to support.":
        "Consiz में एक अनपेक्षित त्रुटि आई और उसे रुकना पड़ा।\n\nब्योरा यहाँ सहेजा गया है:\n{path}\n\nकृपया वह फ़ाइल सहायता को भेजें।",

    # ------------------------------------------------------------------ tray menu
    "⏸ Consiz is paused": "⏸ Consiz रुका हुआ है",
    "⚡ Consiz is active": "⚡ Consiz चालू है",
    "▶ Resume Consiz": "▶ Consiz फिर चालू करें",
    "⏸ Pause Consiz": "⏸ Consiz रोकें",
    "Explain Selection ({key})": "चुना हुआ समझाएँ ({key})",
    "Ask about my PC ({key})": "मेरे पीसी के बारे में पूछें ({key})",
    "Voice Dictate ({key})": "बोलकर पूछें ({key})",
    "🌐 Answer Language": "🌐 उत्तर की भाषा",
    "Auto (Match selection)": "अपने आप (चयन जैसी)",
    "🖱 Trigger": "🖱 ट्रिगर",
    "Middle click": "मिडिल क्लिक",
    "Ctrl + middle click": "Ctrl + मिडिल क्लिक",
    "Keyboard only": "केवल कीबोर्ड",
    "🗂 Recent chats": "🗂 हाल की बातचीत",
    "Saving chats is off (Settings > General)": "बातचीत सहेजना बंद है (Settings > General)",
    "No saved chats yet": "अभी कोई सहेजी हुई बातचीत नहीं",
    "Open the chats folder": "बातचीत का फ़ोल्डर खोलें",
    "⚙️ Settings…": "⚙️ सेटिंग्स…",
    "Start on Windows Boot": "Windows चालू होने पर शुरू करें",
    "⬆ Download Consiz {version}": "⬆ Consiz {version} डाउनलोड करें",
    "Help && diagnostics": "सहायता && डायग्नोस्टिक्स",
    "Copy diagnostics for support": "सहायता के लिए डायग्नोस्टिक्स कॉपी करें",
    "Sign in…": "साइन इन…",
    "Exit Consiz": "Consiz बंद करें",
    "Consiz is paused. It will not touch your mouse or keyboard.": "Consiz रुका हुआ है। यह आपके माउस या कीबोर्ड को नहीं छुएगा।",
    "Consiz is running": "Consiz चल रहा है",
    "Select any text, then press the middle mouse button.": "कोई भी टेक्स्ट चुनें, फिर माउस का मिडिल बटन दबाएँ।",
    "Diagnostics copied. Paste them into your message to support.": "डायग्नोस्टिक्स कॉपी हो गए। उन्हें सहायता को अपने संदेश में पेस्ट करें।",
    "The download link is not set yet. Please ask the person who shared Consiz with you.": "डाउनलोड लिंक अभी सेट नहीं है। कृपया जिसने आपको Consiz दिया उनसे पूछें।",
    "Consiz updates": "Consiz अपडेट",
    "Consiz update": "Consiz अपडेट",
    "Your PC is slow": "आपका पीसी धीमा है",
    "Memory is almost full": "मेमोरी लगभग भरी है",
    "Your disk is almost full": "आपकी डिस्क लगभग भरी है",
    "It has been very busy for 3 minutes. Press {key} and ask Consiz why.": "यह 3 मिनट से बहुत व्यस्त है। {key} दबाएँ और Consiz से कारण पूछें।",
    "It has been very busy for 3 minutes. Biggest: {top}. Press {key} and ask Consiz why.": "यह 3 मिनट से बहुत व्यस्त है। सबसे ज़्यादा: {top}। {key} दबाएँ और Consiz से कारण पूछें।",
    "{percent}% of memory has been in use for 2 minutes. Press {key} to ask Consiz.": "2 मिनट से {percent}% मेमोरी इस्तेमाल में है। Consiz से पूछने के लिए {key} दबाएँ।",
    "{percent}% of memory has been in use for 2 minutes. Biggest: {top}. Press {key} to ask Consiz.": "2 मिनट से {percent}% मेमोरी इस्तेमाल में है। सबसे ज़्यादा: {top}। Consiz से पूछने के लिए {key} दबाएँ।",
    "Drive {drive} has only {gb} GB free ({percent}%). Press {key} to ask Consiz how to free space.": "ड्राइव {drive} में सिर्फ़ {gb} GB खाली है ({percent}%)। जगह खाली करने का तरीका Consiz से पूछने के लिए {key} दबाएँ।",

    # ------------------------------------------------------------------ sign-in, welcome, settings (every widget text)
    "A little about you": "आपके बारे में थोड़ा",
    "Accessibility": "सुगम्यता",
    "Account": "खाता",
    "Always blocked: password managers, remote desktop, and any window whose title looks like a password, bank, wallet or private-browsing page. Add your own words below, separated by commas (a window whose title or program name contains one is never read).":
        "हमेशा बंद: पासवर्ड मैनेजर, रिमोट डेस्कटॉप, और ऐसी कोई भी विंडो जिसका शीर्षक पासवर्ड, बैंक, वॉलेट या प्राइवेट ब्राउज़िंग जैसा लगे। अपने शब्द नीचे कॉमा से अलग करके जोड़ें (जिस विंडो के शीर्षक या प्रोग्राम के नाम में इनमें से कोई शब्द हो, उसे कभी नहीं पढ़ा जाएगा)।",
    "Answer": "उत्तर",
    "Answer language": "उत्तर की भाषा",
    "Answer window": "उत्तर विंडो",
    "Back": "पीछे",
    "Built in: 3dsmax.exe, acad.exe, blender.exe, fusion360.exe, godot.exe, maya.exe and other 3D / CAD tools. Add your own program names, separated by commas (for example: vlc.exe, mpc-hc64.exe).":
        "पहले से शामिल: 3dsmax.exe, acad.exe, blender.exe, fusion360.exe, godot.exe, maya.exe और अन्य 3D / CAD टूल। अपने प्रोग्राम के नाम कॉमा से अलग करके जोड़ें (जैसे: vlc.exe, mpc-hc64.exe)।",
    "Changes apply at once.": "बदलाव तुरंत लागू होते हैं।",
    "Chat history": "बातचीत का इतिहास",
    "Check for updates": "अपडेट देखें",
    "Choose your AI": "अपना AI चुनें",
    "Clear local data…": "स्थानीय डेटा मिटाएँ…",
    "Clears your settings, the saved sign-in and the app log from this computer. Your profile.md is kept. Consiz shows the welcome screens again next time it starts.":
        "इस कंप्यूटर से आपकी सेटिंग्स, सहेजा हुआ साइन-इन और ऐप का लॉग मिटा देता है। आपकी profile.md सुरक्षित रहती है। अगली बार शुरू होने पर Consiz फिर से स्वागत स्क्रीन दिखाएगा।",
    "Cloud (Consiz) — fast, free to start, sign in with Google": "क्लाउड (Consiz) — तेज़, शुरू करना मुफ़्त, Google से साइन इन करें",
    "Consiz Settings": "Consiz सेटिंग्स",
    "Consiz cloud (needs internet; sign in with Google)": "Consiz क्लाउड (इंटरनेट चाहिए; Google से साइन इन करें)",
    "Consiz follows the Windows settings for Text size and High contrast (restart Consiz after changing them). Every button in the answer window can be reached with the Tab key and pressed with Enter or Space. On while a screen reader is running.":
        "Consiz, Windows की टेक्स्ट साइज़ और हाई कॉन्ट्रास्ट सेटिंग्स का पालन करता है (इन्हें बदलने के बाद Consiz दोबारा शुरू करें)। उत्तर विंडो के हर बटन तक Tab कुंजी से पहुँचा जा सकता है और Enter या Space से दबाया जा सकता है। स्क्रीन रीडर चलने पर यह अपने आप चालू रहता है।",
    "Consiz is a lightweight, thoughtful assistant living quietly in the background of your Windows PC.\n\nSelect anything on your screen — a sentence, a complex document, code, or a folder — then press the middle mouse button (or Ctrl+Alt+S).\n\nConsiz explains, answers, or summarizes it immediately next to your cursor. No window switching, no manual copying.":
        "Consiz एक हल्का, समझदार सहायक है जो आपके Windows पीसी में चुपचाप बैकग्राउंड में रहता है।\n\nस्क्रीन पर कुछ भी चुनें — एक वाक्य, कोई जटिल दस्तावेज़, कोड या फ़ोल्डर — फिर माउस का मिडिल बटन दबाएँ (या Ctrl+Alt+S)।\n\nConsiz उसे तुरंत आपके कर्सर के पास समझाता, उसका उत्तर देता या सारांश बनाता है। न विंडो बदलनी पड़ती है, न हाथ से कॉपी करना पड़ता है।",
    "Consiz is now running quietly in your Windows system tray.\n\n•  Select text or a file, then press middle mouse (or Ctrl+Alt+S) — Consiz explains, answers, or summarizes immediately.\n\n•  Type a follow-up question right in the answer popup and press Enter.\n\n•  Click Copy on any answer to paste it into your active document.\n\n•  Right-click the Consiz tray icon anytime for settings, model preferences, and language selection.":
        "Consiz अब आपके Windows सिस्टम ट्रे में चुपचाप चल रहा है।\n\n•  टेक्स्ट या फ़ाइल चुनें, फिर माउस का मिडिल बटन दबाएँ (या Ctrl+Alt+S) — Consiz तुरंत समझाता, उत्तर देता या सारांश बनाता है।\n\n•  उत्तर पॉपअप में ही अगला सवाल टाइप करें और Enter दबाएँ।\n\n•  किसी भी उत्तर पर \"कॉपी\" दबाकर उसे अपने खुले दस्तावेज़ में पेस्ट करें।\n\n•  सेटिंग्स, मॉडल की पसंद और भाषा चुनने के लिए कभी भी Consiz ट्रे आइकन पर राइट-क्लिक करें।",
    "Consiz uses this to personalize answers and drafts so they sound like you — never shared with anyone, and skipped entirely for plain factual queries.":
        "Consiz इसका उपयोग उत्तरों और ड्राफ़्ट को आपकी शैली में ढालने के लिए करता है — यह किसी के साथ साझा नहीं किया जाता, और सीधे तथ्य वाले सवालों में बिल्कुल इस्तेमाल नहीं होता।",
    "Continue": "आगे बढ़ें",
    "Continue with Google": "Google के साथ जारी रखें",
    "Copy diagnostics": "डायग्नोस्टिक्स कॉपी करें",
    "Ctrl + middle click only (normal clicks are never touched)": "केवल Ctrl + मिडिल क्लिक (सामान्य क्लिक को कभी नहीं छेड़ा जाता)",
    "Delete all saved chats": "सभी सहेजी हुई बातचीत मिटाएँ",
    "Drag the corner of the answer window to resize it: Consiz remembers the size.": "उत्तर विंडो का आकार बदलने के लिए उसका कोना खींचें: Consiz आकार याद रखता है।",
    "Explain selection": "चुना हुआ समझाएँ",
    "Finish Setup": "सेटअप पूरा करें",
    "Forget my permission": "मेरी अनुमति भूल जाएँ",
    "Forget windows I allowed": "मेरी अनुमति वाली विंडो भूल जाएँ",
    "Get Started": "शुरू करें",
    "Get a free key at: openrouter.ai/keys": "मुफ़्त कुंजी यहाँ से लें: openrouter.ai/keys",
    "Help": "सहायता",
    "How to start Consiz with the mouse": "माउस से Consiz कैसे शुरू करें",
    "If the cloud cannot be reached, answer offline when Ollama is running": "क्लाउड न मिले तो, Ollama चल रहा हो तब ऑफ़लाइन उत्तर दें",
    "Keep my chats on this PC so I can open them again": "मेरी बातचीत इस पीसी पर रखें ताकि मैं उन्हें फिर खोल सकूँ",
    "Keyboard only (the mouse is never touched)": "केवल कीबोर्ड (माउस को कभी नहीं छेड़ा जाता)",
    "Keyboard shortcuts": "कीबोर्ड शॉर्टकट",
    "Let me speak to Consiz (microphone button and the Voice shortcut)": "मुझे Consiz से बोलने दें (माइक्रोफ़ोन बटन और वॉइस शॉर्टकट)",
    "Middle click (given back to the app when nothing is selected)": "मिडिल क्लिक (कुछ चुना न हो तो ऐप को वापस दे दिया जाता है)",
    "Move the keyboard focus into the answer window when it opens": "उत्तर विंडो खुलने पर कीबोर्ड फ़ोकस उसमें ले जाएँ",
    "Not allowed yet. Consiz asks the first time you use Ask about my PC.": "अभी अनुमति नहीं है। \"मेरे पीसी के बारे में पूछें\" पहली बार इस्तेमाल करने पर Consiz पूछेगा।",
    "Not signed in.": "साइन इन नहीं है।",
    "Off until you turn it on. Chats are saved only on this PC, never uploaded, with passwords and keys removed first. Tray > Recent chats opens one again. Each chat can also be saved as a text file from its window (Save as text), whether or not this is on.":
        "जब तक आप चालू न करें, बंद रहता है। बातचीत केवल इसी पीसी पर सहेजी जाती है, कभी अपलोड नहीं होती, और पासवर्ड व कुंजियाँ पहले हटा दी जाती हैं। ट्रे > हाल की बातचीत से कोई बातचीत फिर खुलती है। हर बातचीत को उसकी विंडो से टेक्स्ट फ़ाइल के रूप में भी सहेजा जा सकता है (टेक्स्ट के रूप में सहेजें), चाहे यह चालू हो या नहीं।",
    "Off until you turn it on. Every 30 seconds Consiz reads three numbers on this PC (CPU, memory, free disk). Nothing is sent anywhere, no AI is used, nothing is stored and nothing is closed. It only shows one small message when something stays high for a few minutes.":
        "जब तक आप चालू न करें, बंद रहता है। हर 30 सेकंड में Consiz इस पीसी पर तीन संख्याएँ पढ़ता है (CPU, मेमोरी, खाली डिस्क)। कुछ भी कहीं नहीं भेजा जाता, कोई AI इस्तेमाल नहीं होता, कुछ भी सहेजा नहीं जाता और कुछ भी बंद नहीं किया जाता। जब कुछ मिनटों तक कोई चीज़ ऊँची बनी रहती है, तभी एक छोटा संदेश दिखता है।",
    "Offline (gemma4:e4b) — private, runs locally via Ollama": "ऑफ़लाइन (gemma4:e4b) — निजी, Ollama से इसी पीसी पर चलता है",
    "Offline on this PC (gemma4:e4b through Ollama): private, slower": "इस पीसी पर ऑफ़लाइन (Ollama से gemma4:e4b): निजी, धीमा",
    "Open log folder": "लॉग फ़ोल्डर खोलें",
    "Open the folder": "फ़ोल्डर खोलें",
    "PC watcher": "पीसी निगरानी",
    "Pause": "रोकें",
    "Pause Consiz now (mouse and shortcuts go back to your apps)": "Consiz को अभी रोकें (माउस और शॉर्टकट आपके ऐप्स को वापस मिल जाते हैं)",
    "Pause the mouse trigger while a full-screen app or a presentation is in front": "फ़ुल-स्क्रीन ऐप या प्रेज़ेंटेशन सामने होने पर माउस ट्रिगर रोक दें",
    "Permission": "अनुमति",
    "Programs where the middle button is left alone": "वे प्रोग्राम जहाँ मिडिल बटन को छेड़ा नहीं जाता",
    "Reset answer window size": "उत्तर विंडो का आकार रीसेट करें",
    "Reset to default": "डिफ़ॉल्ट पर लौटें",
    "Runs on your local Ollama instance (gemma4:e4b).": "आपके अपने Ollama (gemma4:e4b) पर चलता है।",
    "STEP 1 OF 4": "चरण 1 / 4",
    "STEP 2 OF 4": "चरण 2 / 4",
    "STEP 3 OF 4": "चरण 3 / 4",
    "STEP 4 OF 4": "चरण 4 / 4",
    "Save": "सहेजें",
    "Save Key": "कुंजी सहेजें",
    "Save shortcuts": "शॉर्टकट सहेजें",
    "Settings": "सेटिंग्स",
    "Sign in": "साइन इन",
    "Sign in once to start using Consiz.": "Consiz इस्तेमाल करना शुरू करने के लिए एक बार साइन इन करें।",
    "Sign in to Consiz": "Consiz में साइन इन करें",
    "Sign out": "साइन आउट",
    "Speech model: downloaded, works offline ✓": "बोली पहचानने का मॉडल: डाउनलोड हो चुका है, ऑफ़लाइन चलता है ✓",
    "Speech model: not downloaded yet. Consiz asks once, then downloads about {mb} MB the first time you speak.":
        "बोली पहचानने का मॉडल: अभी डाउनलोड नहीं हुआ है। Consiz एक बार पूछता है, फिर पहली बार बोलने पर लगभग {mb} MB डाउनलोड करता है।",
    "Start Consiz when I sign in to Windows": "Windows में साइन इन करने पर Consiz शुरू करें",
    "Start with Windows": "Windows के साथ शुरू करें",
    "Tell me when my PC has been slow, full or short of disk space": "जब मेरा पीसी धीमा हो, भरा हो या डिस्क की जगह कम हो, तो मुझे बताएँ",
    "To change or pull another model:\n  ollama pull gemma4:e4b": "दूसरा मॉडल बदलने या खींचने के लिए:\n  ollama pull gemma4:e4b",
    "Use two modifiers (for example Ctrl+Alt+S) or one modifier with a function key (Ctrl+F9). A shortcut such as Ctrl+S alone would break Save in every app, so it is refused.":
        "दो मॉडिफ़ायर कुंजियाँ (जैसे Ctrl+Alt+S) या एक मॉडिफ़ायर के साथ फ़ंक्शन कुंजी (Ctrl+F9) इस्तेमाल करें। Ctrl+S जैसा अकेला शॉर्टकट हर ऐप में \"सहेजें\" को तोड़ देगा, इसलिए उसे अस्वीकार किया जाता है।",
    "Voice dictation": "वॉइस डिक्टेशन",
    "Welcome to Consiz": "Consiz में आपका स्वागत है",
    "What best describes you?": "आपको कौन-सा वर्णन सबसे अच्छा लगता है?",
    "Where answers come from": "उत्तर कहाँ से आते हैं",
    "Why are you using Consiz?": "आप Consiz क्यों इस्तेमाल कर रहे हैं?",
    "Windows Consiz never reads inside": "वे विंडो जिनके अंदर Consiz कभी नहीं पढ़ता",
    "Windows that run as administrator cannot be reached by the mouse or read by Consiz, unless Consiz is also started as administrator (right-click Consiz.exe, then Run as administrator).":
        "जो विंडो administrator के रूप में चल रही हैं, उन तक माउस नहीं पहुँच सकता और Consiz उन्हें पढ़ भी नहीं सकता, जब तक Consiz को भी administrator के रूप में शुरू न किया जाए (Consiz.exe पर राइट-क्लिक करें, फिर \"Run as administrator\")।",
    "Works across any app (browser, PDF viewer, editor, or Explorer).": "किसी भी ऐप में काम करता है (ब्राउज़र, PDF व्यूअर, एडिटर या Explorer)।",
    "You can change your provider anytime by right-clicking the system tray icon.": "आप कभी भी सिस्टम ट्रे आइकन पर राइट-क्लिक करके अपना प्रदाता बदल सकते हैं।",
    "You're all set!": "सब तैयार है!",
    "Your data on this PC": "इस पीसी पर आपका डेटा",
    "Your name (optional)": "आपका नाम (वैकल्पिक)",
    "Your voice is turned into text on this PC and the audio is never uploaded: only the words you say are sent to the AI, like a typed question.":
        "आपकी आवाज़ इसी पीसी पर टेक्स्ट में बदली जाती है और ऑडियो कभी अपलोड नहीं होता: केवल आपके बोले हुए शब्द AI को भेजे जाते हैं, जैसे टाइप किया हुआ सवाल।",
    "✓ Cloud is ready. Next you will sign in with Google.": "✓ क्लाउड तैयार है। अब आप Google से साइन इन करेंगे।",
    "✦ Trigger: Middle Mouse Click  ·  or  Ctrl+Alt+S": "✦ ट्रिगर: माउस का मिडिल क्लिक  ·  या  Ctrl+Alt+S",

    # ------------------------------------------------------------------ the language setting itself
    "App language": "ऐप की भाषा",
    "The words in Consiz's own windows. Restart Consiz to apply. (The language of the answers is set above, under Answer language.)":
        "Consiz की अपनी विंडो में दिखने वाले शब्द। लागू करने के लिए Consiz दोबारा शुरू करें। (उत्तरों की भाषा ऊपर \"उत्तर की भाषा\" में तय होती है।)",
    "Restart Consiz for the new language to apply.": "नई भाषा लागू करने के लिए Consiz दोबारा शुरू करें।",

    # ------------------------------------------------------------------ tabs, titles, status lines, voice instructions
    "General": "सामान्य",
    "Mouse": "माउस",
    "Shortcuts": "शॉर्टकट",
    "PC mode": "पीसी मोड",
    "Account & data": "खाता और डेटा",
    "Meaning": "अर्थ",
    "Explained": "समझाया गया",
    "Summary": "सारांश",
    "Code explained": "कोड समझाया गया",
    "Calculation": "गणना",
    "Folder Analysis": "फ़ोल्डर विश्लेषण",
    "Selection": "चयन",
    "Picture": "तस्वीर",
    "Data": "डेटा",
    "Action Completed": "क्रिया पूरी हुई",
    "🎙 Voice": "🎙 आवाज़",
    "Speak what to do with the selected text": "चुने हुए टेक्स्ट के साथ क्या करना है, बोलिए",
    "- Speak what to do with the selected text, then pause:": "- चुने हुए टेक्स्ट के साथ क्या करना है, बोलिए, फिर रुकिए:",
    "• 'Summarize this in 3 bullets'": "• 'इसका 3 बिंदुओं में सारांश बनाओ'",
    "• 'Translate this into Gujarati / Hindi / Spanish'": "• 'इसका गुजराती / हिंदी / स्पेनिश में अनुवाद करो'",
    "• 'Explain what this code does'": "• 'समझाओ कि यह कोड क्या करता है'",
    "• 'Draft a polite reply'": "• 'एक विनम्र जवाब का ड्राफ़्ट बनाओ'",
    "• 'Copy to clipboard'": "• 'क्लिपबोर्ड पर कॉपी करो'",
    "- It stops by itself when you pause (or press Ctrl+Alt+D / ■).": "- आपके रुकने पर यह अपने आप रुक जाता है (या Ctrl+Alt+D / ■ दबाएँ)।",
    "Saved ✓": "सहेजा गया ✓",
    "Answer language saved ✓": "उत्तर की भाषा सहेजी गई ✓",
    "AI source saved ✓": "AI स्रोत सहेजा गया ✓",
    "Voice model saved ✓": "वॉइस मॉडल सहेजा गया ✓",
    "Paste a key first.": "पहले कोई कुंजी पेस्ट करें।",
    "Key saved ✓": "कुंजी सहेजी गई ✓",
    "Program list saved ✓": "प्रोग्राम सूची सहेजी गई ✓",
    "That shortcut is not allowed. Try Ctrl+Alt+<letter>.": "यह शॉर्टकट मान्य नहीं है। Ctrl+Alt+<अक्षर> आज़माएँ।",
    "The shortcuts must all be different.": "सभी शॉर्टकट अलग-अलग होने चाहिए।",
    "Shortcuts saved ✓ (active within a few seconds)": "शॉर्टकट सहेजे गए ✓ (कुछ सेकंड में चालू हो जाएँगे)",
    "Consiz will ask again next time ✓": "Consiz अगली बार फिर पूछेगा ✓",
    "Windows will ask permission again ✓": "विंडो अगली बार फिर अनुमति माँगेंगी ✓",
    "Never-read list saved ✓": "कभी-न-पढ़ने वाली सूची सहेजी गई ✓",
    "Signed out ✓": "साइन आउट हो गया ✓",
    "Signed in ✓": "साइन इन हो गया ✓",
    "Answer window size reset ✓": "उत्तर विंडो का आकार रीसेट हो गया ✓",
    "Diagnostics copied. Paste them into your message to support ✓": "डायग्नोस्टिक्स कॉपी हो गए। उन्हें सहायता को अपने संदेश में पेस्ट करें ✓",
    "There are no saved chats.": "कोई सहेजी हुई बातचीत नहीं है।",
    "Deleted {n} chats ✓": "{n} बातचीत मिटाई गई ✓",
    "Delete all {n} saved chats from this PC? This cannot be undone.": "इस पीसी से सभी {n} सहेजी हुई बातचीत मिटाएँ? इसे वापस नहीं किया जा सकता।",
    "Clear local data": "स्थानीय डेटा मिटाएँ",
    "Clear Consiz's settings, saved sign-in and log from this PC?\n\nYou will be signed out. Consiz stays running until you restart it.":
        "इस पीसी से Consiz की सेटिंग्स, सहेजा हुआ साइन-इन और लॉग मिटाएँ?\n\nआप साइन आउट हो जाएँगे। Consiz तब तक चलता रहेगा जब तक आप उसे दोबारा शुरू नहीं करते।",
    "Done ({n} item(s)). Restart Consiz to finish ✓": "हो गया ({n} चीज़ें)। पूरा करने के लिए Consiz दोबारा शुरू करें ✓",
    "Auto (matches the selected text)": "अपने आप (चुने हुए टेक्स्ट के अनुसार)",
    "Checking for Ollama…": "Ollama की जाँच हो रही है…",
    "⚠ Paste your OpenRouter API key first.": "⚠ पहले अपनी OpenRouter API कुंजी पेस्ट करें।",
    "⚠ That doesn't look like an OpenRouter key (should start with sk-or-).": "⚠ यह OpenRouter कुंजी जैसी नहीं लगती (sk-or- से शुरू होनी चाहिए)।",
    "✓ Key saved — Cloud is ready!": "✓ कुंजी सहेजी गई — क्लाउड तैयार है!",
    "✓ Key saved — Cloud is ready.": "✓ कुंजी सहेजी गई — क्लाउड तैयार है।",
    "Paste your free OpenRouter key above, then click Save Key.": "ऊपर अपनी मुफ़्त OpenRouter कुंजी पेस्ट करें, फिर \"कुंजी सहेजें\" दबाएँ।",
    "Finish signing in in your browser…": "अपने ब्राउज़र में साइन इन पूरा करें…",
}
